---
title: "Welcome!"
description: |
  Something about me and my blog 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


### Hi, I am Teresa Chen!  

I joined the Department of Physical Therapy at Ithaca College as an Assistant Professor in August, 2020. I received my education in Physical Therapy at the [National Taiwan University](https://www.mc.ntu.edu.tw/ntupt/Index.action) and PhD degree in [Human Physiology](https://physiology.uoregon.edu/) at the University of Oregon with a focus on biomechanics.   

I aims to develop a career in the direction of mobility impairment research with translational applications to patient care and exercise performance. Currently, my research interest focuses on age-related and injury-induced declines in cognitive and physical functions and their contributions to gait imbalance and falls as well as on the impact-induced sports injuries, ultimately leading to new rehabilitation examination and interventions.  

Prior to doctoral training, I worked alongside Olympic weightlifters as a physical therapist. I found this job challenging yet satisfying through implementing preventive programs, developing and carrying out rehabilitation programs, and assisting in international meets for elite athletes. The best part was that I had the opportunity to travel to different countries and witness some of the greatest competitions in the world.  

Inspired by [my athletes](https://en.wikipedia.org/wiki/Kuo_Hsing-chun), I enjoy weightlifting during her free time. I also like to run, hike, watch movies, discover new places to eat and keep exploring new interests. After immersing meself in Eugene’s ever-changing beauty and outdoor activities, I cannot wait to explore the waterfalls and trails in Ithaca!



### Contact

Feel free to contact me via [email at schen3@ithaca.edu](mailto:schen3@ithaca.edu)

### About this blog

--------------------------------------------------------------------------------------------
Time                Milestone
------------------  -------------------------------------------------------------------------
  March, 2019       Final project in [Communicating and Transforming Data](https://uo-datasci-specialization.github.io/c2-communicate_transform_data/) is done!

  Febrary, 2019     This blog is created with a purpose of fullfill one of the requirment of class final project in [Communicating and Transforming Data](https://uo-datasci-specialization.github.io/c2-communicate_transform_data/).
-------------------------------------------------------------

